# keymap.toml
# [[manager.prepend_keymap]]
# on   = "<C-p>"
# run  = "shell 'for f in $@; do mplayer \"$f\" >/dev/null 2>&1 & done'"
# desc = "Play selected audio files"
# [[manager.prepend_keymap]]
# on   = "<C-P>"
# run  = "shell --block 'for f in $@; do mpv --no-terminal --no-video \"$f\" >/dev/null 2>&1 & done'"
# desc = "Play selected audio files"
[[manager.prepend_keymap]]
on   = "<C-p>"
run  = "shell --block 'for ii in \"$@\"; do mplayer \"$ii\"; done'"
desc = "Play selected audio files"
